# -*- coding: utf-8 -*-
"""CV-lab-03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5R5GjuplpEJCYIeTGuCho8UEYUrUi3n
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

def shpw_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title("Original grayscale image")
  plt.axis('off')
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title("Average Filter (3x3)")
  plt.axis('off')
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title("Average Filter (5x5)")
  plt.axis('off')
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title("Average Filter (7x7)")
  plt.axis('off')
  plt.tight_layout()
  plt.show()

img=cv2.imread('/content/drive/MyDrive/1_-x3F59-3Ap0TaiJ7-fS4Sw.png',0)

if img is None:
  print("Error image not found")
else:
  Kernel_3x3=np.ones((3,3),np.float32)/9
  Kernel_5x5=np.ones((5,5),np.float32)/25
  Kernel_7x7=np.ones((7,7),np.float32)/49
  blur_3x3=cv2.filter2D(img,-1,Kernel_3x3)
  blur_5x5=cv2.filter2D(img,-1,Kernel_5x5)
  blur_7x7=cv2.filter2D(img,-1,Kernel_7x7)
  shpw_comparison(img,blur_3x3,blur_5x5,blur_7x7)

import numpy as np
import matplotlib.pyplot as plt
kernel = np.ones((15,15)) * 1/225
k_s = 15
m = img.shape[0]
n = img.shape[1]
filtered_img = np.zeros((m - k_s + 1, n - k_s + 1), dtype=img.dtype)
for i in range(m - k_s + 1):
   for j in range(n - k_s + 1):
      image_region = img[i:i+k_s, j:j+k_s]

      filtered_img[i, j] = np.sum(kernel * image_region)
plt.imshow(filtered_img, cmap='gray')
plt.title(f'Manually Filtered Image ({k_s}x{k_s})')
plt.axis('off')
plt.show()